### ISSUE TITLE
Not found for plugin in maven 7.10.3

### ISSUE THREAD

**Issue by MrHDOLEK** [allegro/elasticsearch-analysis-morfologik#36]
Hi 
During installation I get an error from the maven repository of your plugin ze not found.
Es version: 7.10.3
https://repo1.maven.org/maven2/pl/allegro/tech/elasticsearch/plugin/elasticsearch-analysis-morfologik/7.10.3/elasticsearch-analysis-morfologik-7.10.3.zip
```bash
bin/elasticsearch-plugin install pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:7.10.3
-> Installing pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:7.10.3
-> Downloading pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:7.10.3 from maven central
-> Failed installing pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:7.10.3
-> Rolling back pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:7.10.3
-> Rolled back pl.allegro.tech.elasticsearch.plugin:elasticsearch-analysis-morfologik:7.10.3
Exception in thread "main" java.io.FileNotFoundException: https://repo1.maven.org/maven2/pl/allegro/tech/elasticsearch/plugin/elasticsearch-analysis-morfologik/7.10.3/elasticsearch-analysis-morfologik-7.10.3.zip
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1928)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1528)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadZip(InstallPluginCommand.java:448)
        at org.elasticsearch.plugins.InstallPluginCommand.downloadAndValidate(InstallPluginCommand.java:525)
        at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:315)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:251)
        at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:224)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:91)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)

```

**Comment by pbobruk** [comment]
Hi, version 7.10.3 doesn't appear in the elasticsearch version lists:
https://github.com/elastic/elasticsearch/releases?q=7.10.3&expanded=true

Maybe you meant a different version?
